export type BadanieCat = "Kardiologiczne" | "Pediatryczne" | "USG / Doppler" | "Sen i oddech" | "Ocena ryzyka"

export type BadanieSubpageData = {
  slug: string
  title: string
  cat: BadanieCat
  metaTitle: string
  metaDescription: string
  heroBody: string
  duration: string
  what: { heading: string; body: string }
  how: { heading: string; body: string }
  prep: string[]
  indications: string[]
}

// One hero image per category — there is no per-test photography.
export const catHeroImage: Record<BadanieCat, string> = {
  "Kardiologiczne": "/images/kardiologia-2.webp",
  "Pediatryczne": "/images/kardiologia-3.webp",
  "USG / Doppler": "/images/philips-affiniti-50.webp",
  "Sen i oddech": "/images/badania-9.webp",
  "Ocena ryzyka": "/images/badania-9.webp",
}

export const badaniaSubpages: BadanieSubpageData[] = [
  // ── Kardiologiczne ──
  {
    slug: "proba-wysilkowa-z-saturacja",
    title: "Próba wysiłkowa z saturacją",
    cat: "Kardiologiczne",
    metaTitle: "Próba wysiłkowa z saturacją Lublin — Elkardia",
    metaDescription: "Próba wysiłkowa z jednoczesnym pomiarem saturacji krwi — ocena wydolności serca i utlenowania podczas wysiłku. Badanie w Elkardii w Lublinie.",
    heroBody: "Klasyczna próba wysiłkowa rozszerzona o ciągły pomiar wysycenia krwi tlenem — pozwala wychwycić desaturację, która ujawnia się dopiero pod obciążeniem.",
    duration: "ok. 30–45 minut",
    what: {
      heading: "Czym jest próba wysiłkowa z saturacją?",
      body: "To badanie łączy standardowy test wysiłkowy EKG z pulsoksymetrią prowadzoną przez cały czas trwania wysiłku. Oprócz zapisu EKG, ciśnienia i tolerancji obciążenia rejestrujemy wysycenie hemoglobiny tlenem (SpO2). Dzięki temu wykrywamy spadki saturacji, które w spoczynku pozostają niewidoczne, a pojawiają się dopiero przy zwiększonym zapotrzebowaniu na tlen. Badanie jest szczególnie przydatne u pacjentów, u których duszność wysiłkowa może mieć przyczynę zarówno sercową, jak i płucną — pozwala rozróżnić te dwa mechanizmy w trakcie jednego testu.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent maszeruje na bieżni lub pedałuje na cykloergometrze według ustalonego protokołu, w którym obciążenie rośnie stopniowo co kilka minut. Przez cały czas rejestrujemy 12-odprowadzeniowe EKG, mierzymy ciśnienie tętnicze, a czujnik pulsoksymetru na palcu monitoruje saturację. Test prowadzi lekarz wraz z technikiem i przerywa go po osiągnięciu limitu tętna, wystąpieniu objawów lub zmian w zapisie. Po zakończeniu wysiłku pozostajemy przy pacjencie jeszcze przez kilka minut fazy odpoczynku, ponieważ część nieprawidłowości ujawnia się właśnie wtedy.",
    },
    prep: [
      "Lekki posiłek najpóźniej 2 godziny przed badaniem",
      "Wygodny strój sportowy i obuwie na zmianę",
      "Lista przyjmowanych leków — o ewentualnym odstawieniu decyduje lekarz",
      "Bez kawy i papierosów w dniu badania",
    ],
    indications: [
      "Duszność wysiłkowa o niejasnej przyczynie",
      "Podejrzenie choroby niedokrwiennej serca",
      "Ocena tolerancji wysiłku u pacjentów z chorobą płuc i serca",
      "Kwalifikacja do rehabilitacji kardiologicznej",
      "Ocena skuteczności leczenia",
    ],
  },
  {
    slug: "holter-ekg-24h",
    title: "Holter EKG 24h standard",
    cat: "Kardiologiczne",
    metaTitle: "Holter EKG 24h Lublin — Elkardia",
    metaDescription: "Całodobowe monitorowanie EKG metodą Holtera — rejestracja rytmu serca podczas normalnej aktywności. Badanie w Elkardii w Lublinie.",
    heroBody: "Całodobowy zapis pracy serca podczas zwykłej aktywności — wychwytuje zaburzenia rytmu, które w krótkim badaniu EKG pozostają niewidoczne.",
    duration: "24 godziny rejestracji",
    what: {
      heading: "Czym jest Holter EKG?",
      body: "Holter EKG to niewielki rejestrator noszony przez dobę, który zapisuje każde uderzenie serca. Standardowe EKG spoczynkowe trwa kilkanaście sekund i wychwytuje tylko to, co dzieje się w danej chwili — tymczasem arytmie bywają napadowe i pojawiają się nieregularnie. Całodobowy zapis pozwala powiązać odczuwane objawy, takie jak kołatanie serca czy zasłabnięcie, z rzeczywistym zapisem elektrycznym z tego samego momentu. To podstawowe badanie w diagnostyce zaburzeń rytmu i przewodzenia.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Technik przykleja na klatce piersiowej kilka elektrod i podłącza je do rejestratora wielkości telefonu, noszonego na pasku lub w kieszeni. Pacjent wraca do domu i prowadzi zupełnie normalny tryb życia — to warunek wiarygodności badania. Równolegle prowadzi krótki dzienniczek, w którym notuje godziny snu, wysiłku i wszelkich objawów. Po dobie wraca do pracowni, gdzie zdejmujemy urządzenie i wczytujemy zapis. Lekarz analizuje pełny materiał i zestawia go z dzienniczkiem.",
    },
    prep: [
      "Kąpiel przed założeniem rejestratora — w trakcie badania nie można się kąpać",
      "Panowie z owłosioną klatką piersiową: konieczne wygolenie miejsc pod elektrody",
      "Bawełniana koszulka i strój na zmianę",
      "Prowadzenie dzienniczka aktywności i objawów",
    ],
    indications: [
      "Kołatania serca i uczucie nierównej pracy serca",
      "Zasłabnięcia i omdlenia o niejasnej przyczynie",
      "Podejrzenie napadowego migotania przedsionków",
      "Ocena skuteczności leczenia antyarytmicznego",
      "Podejrzenie zaburzeń przewodzenia i pauz",
    ],
  },
  {
    slug: "holter-ekg-12-kanalowy",
    title: "Holter EKG 12-kanałowy",
    cat: "Kardiologiczne",
    metaTitle: "Holter EKG 12-kanałowy Lublin — Elkardia",
    metaDescription: "Holter EKG w pełnym zapisie 12-odprowadzeniowym — precyzyjna lokalizacja arytmii i ocena niedokrwienia. Badanie w Elkardii w Lublinie.",
    heroBody: "Holter w pełnym zapisie 12-odprowadzeniowym — pozwala nie tylko wykryć arytmię, ale też precyzyjnie wskazać miejsce jej powstawania.",
    duration: "24 godziny rejestracji",
    what: {
      heading: "Czym różni się Holter 12-kanałowy?",
      body: "Standardowy Holter rejestruje serce z 3 kanałów, co wystarcza do wykrycia zaburzeń rytmu. Wersja 12-kanałowa zapisuje pełny obraz odpowiadający klasycznemu 12-odprowadzeniowemu EKG, tyle że przez całą dobę. Ta różnica ma znaczenie tam, gdzie liczy się nie sam fakt wystąpienia arytmii, lecz jej dokładna lokalizacja — na przykład przy kwalifikacji do ablacji, gdy elektrofizjolog musi ocenić morfologię pobudzeń. Pełny zapis pozwala też rzetelniej ocenić zmiany niedokrwienne odcinka ST.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Zakładanie wygląda podobnie jak przy Holterze standardowym, ale elektrod jest więcej — rozmieszczamy je zgodnie ze schematem 12-odprowadzeniowym, co wymaga starannego przygotowania skóry. Pacjent nosi rejestrator przez dobę, prowadząc normalną aktywność i notując objawy w dzienniczku. Po zwróceniu urządzenia lekarz analizuje pełny materiał — ocenia rodzaj i liczbę pobudzeń, ich morfologię oraz zachowanie odcinka ST w ciągu doby.",
    },
    prep: [
      "Kąpiel przed założeniem rejestratora",
      "Konieczne wygolenie klatki piersiowej u panów — elektrod jest więcej niż zwykle",
      "Bawełniana koszulka i strój na zmianę",
      "Prowadzenie dzienniczka aktywności i objawów",
    ],
    indications: [
      "Kwalifikacja do ablacji — ocena morfologii pobudzeń",
      "Liczne dodatkowe pobudzenia komorowe wymagające lokalizacji",
      "Podejrzenie zmian niedokrwiennych w ciągu doby",
      "Arytmie wymagające precyzyjnej diagnostyki przed zabiegiem",
    ],
  },
  {
    slug: "holter-ekg-1-8-dniowy",
    title: "Holter EKG 1–8 dniowy",
    cat: "Kardiologiczne",
    metaTitle: "Holter EKG wielodobowy (1–8 dni) Lublin — Elkardia",
    metaDescription: "Wielodobowy Holter EKG do 8 dni — zwiększa szansę wychwycenia rzadkich napadów arytmii. Badanie w Elkardii w Lublinie.",
    heroBody: "Wydłużony zapis EKG trwający nawet 8 dni — dla arytmii, które pojawiają się zbyt rzadko, by uchwycić je w ciągu jednej doby.",
    duration: "od 1 do 8 dni",
    what: {
      heading: "Kiedy potrzebny jest zapis wielodobowy?",
      body: "Jeśli kołatania serca zdarzają się raz na kilka dni, dobowy Holter ma niewielką szansę trafić na napad — ujemny wynik niczego wtedy nie wyklucza. Rejestrator wielodobowy rozwiązuje ten problem, wydłużając obserwację nawet do ośmiu dni i proporcjonalnie zwiększając prawdopodobieństwo zarejestrowania zdarzenia. Urządzenia tego typu są mniejsze i lżejsze od klasycznych Holterów, a część z nich przykleja się bezpośrednio do skóry w formie plastra, co ułatwia noszenie przez tak długi czas.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Zakładamy rejestrator w pracowni i ustalamy planowaną długość zapisu — od jednego do ośmiu dni, zależnie od tego, jak często występują objawy. Pacjent wraca do domu i funkcjonuje normalnie, w tym chodzi do pracy. Przez cały okres prowadzi dzienniczek objawów, a przy każdym epizodzie kołatania naciska przycisk zdarzenia na urządzeniu, co znakuje zapis w tym miejscu. Po umówionym terminie oddaje rejestrator, a lekarz analizuje cały materiał ze szczególnym uwzględnieniem oznaczonych momentów.",
    },
    prep: [
      "Kąpiel przed założeniem — możliwości higieny są ograniczone przez cały okres",
      "Wygolenie miejsc mocowania elektrod",
      "Konsekwentne prowadzenie dzienniczka przez wszystkie dni",
      "Naciskanie przycisku zdarzenia przy każdym objawie",
    ],
    indications: [
      "Rzadkie, napadowe kołatania serca",
      "Ujemny wynik Holtera 24h mimo utrzymujących się objawów",
      "Poszukiwanie napadowego migotania przedsionków",
      "Diagnostyka omdleń o rzadkiej częstotliwości",
    ],
  },
  {
    slug: "rejestratory-arytmii",
    title: "Rejestratory arytmii (monitoring wielomiesięczny)",
    cat: "Kardiologiczne",
    metaTitle: "Rejestratory arytmii — monitoring wielomiesięczny Lublin — Elkardia",
    metaDescription: "Długoterminowe monitorowanie rytmu serca trwające miesiące — dla arytmii występujących bardzo rzadko. Elkardia, Lublin.",
    heroBody: "Monitorowanie rytmu serca liczone w miesiącach, a nie dobach — ostatnia deska ratunku w diagnostyce najrzadszych arytmii i omdleń.",
    duration: "od kilku tygodni do kilkunastu miesięcy",
    what: {
      heading: "Czym jest monitoring wielomiesięczny?",
      body: "Gdy objawy występują raz na kilka tygodni lub miesięcy, nawet ośmiodniowy Holter zwykle zawodzi. W takich sytuacjach stosujemy rejestratory długoterminowe — zewnętrzne urządzenia zdarzeniowe noszone tygodniami albo rejestrator wszczepialny umieszczany podskórnie w krótkim zabiegu w znieczuleniu miejscowym. Ten ostatni pracuje nawet kilkanaście miesięcy i automatycznie zapisuje epizody spełniające zaprogramowane kryteria. To rozwiązanie o największej skuteczności w diagnostyce omdleń o niewyjaśnionej przyczynie.",
    },
    how: {
      heading: "Jak przebiega monitorowanie?",
      body: "Rodzaj urządzenia dobieramy na konsultacji, po ocenie częstości objawów i wcześniejszej diagnostyki. Rejestrator zewnętrzny wydajemy od ręki wraz z instruktażem. Wszczepienie rejestratora podskórnego to zabieg trwający kilkanaście minut, wykonywany w znieczuleniu miejscowym przez niewielkie nacięcie. Następnie pacjent zgłasza się na okresowe kontrole, podczas których odczytujemy zapamiętane epizody. Po ustaleniu rozpoznania lub upływie żywotności baterii urządzenie usuwamy równie prostym zabiegiem.",
    },
    prep: [
      "Konsultacja kardiologiczna kwalifikująca do konkretnego typu rejestratora",
      "Dla rejestratora wszczepialnego — informacja o lekach przeciwkrzepliwych",
      "Zgłaszanie się na umówione kontrole odczytu",
      "Notowanie okoliczności każdego epizodu objawów",
    ],
    indications: [
      "Omdlenia o niewyjaśnionej przyczynie mimo pełnej diagnostyki",
      "Bardzo rzadkie napady kołatania serca",
      "Poszukiwanie migotania przedsionków po udarze kryptogennym",
      "Ocena nawrotów arytmii po ablacji",
    ],
  },
  {
    slug: "holter-cisnieniowy-rr-24h",
    title: "Holter ciśnieniowy RR 24h",
    cat: "Kardiologiczne",
    metaTitle: "Holter ciśnieniowy RR 24h (ABPM) Lublin — Elkardia",
    metaDescription: "Całodobowa automatyczna rejestracja ciśnienia tętniczego (ABPM) — rozpoznanie nadciśnienia i ocena skuteczności leczenia. Elkardia, Lublin.",
    heroBody: "Całodobowy automatyczny pomiar ciśnienia w warunkach codziennych — znacznie wiarygodniejszy niż pojedynczy pomiar w gabinecie.",
    duration: "24 godziny rejestracji",
    what: {
      heading: "Czym jest Holter ciśnieniowy?",
      body: "Holter ciśnieniowy, nazywany też ABPM, to automatyczny aparat mierzący ciśnienie tętnicze co kilkanaście minut przez całą dobę. Pojedynczy pomiar w gabinecie bywa mylący — u części pacjentów ciśnienie rośnie z samego faktu wizyty, u innych wartości prawidłowe w gabinecie maskują nadciśnienie występujące w domu lub w nocy. Całodobowy zapis pokazuje rzeczywisty profil dobowy, w tym kluczowy nocny spadek ciśnienia, którego brak jest niezależnym czynnikiem ryzyka sercowo-naczyniowego.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Na ramię zakładamy mankiet połączony z niewielkim aparatem noszonym na pasku. Urządzenie samo napełnia mankiet co 15–30 minut w dzień i rzadziej w nocy. W momencie pomiaru wystarczy rozluźnić rękę i pozostać nieruchomo przez kilkanaście sekund. Poza tym pacjent prowadzi zwykłą aktywność i notuje w dzienniczku godziny snu, leków i ewentualnych objawów. Po dobie zdejmujemy aparat i generujemy raport z profilem dobowym, który lekarz omawia na wizycie.",
    },
    prep: [
      "Luźna koszula z rękawem — mankiet zakładamy bezpośrednio na ramię",
      "Notowanie godzin przyjmowania leków i snu",
      "Rozluźnienie ręki na czas każdego pomiaru",
      "Bez kąpieli w trakcie badania",
    ],
    indications: [
      "Rozpoznanie i potwierdzenie nadciśnienia tętniczego",
      "Podejrzenie nadciśnienia białego fartucha",
      "Podejrzenie nadciśnienia maskowanego",
      "Ocena skuteczności leczenia hipotensyjnego",
      "Ocena nocnego profilu ciśnienia",
    ],
  },
  {
    slug: "symultaniczny-pomiar-rr",
    title: "Symultaniczny pomiar RR",
    cat: "Kardiologiczne",
    metaTitle: "Symultaniczny pomiar ciśnienia RR Lublin — Elkardia",
    metaDescription: "Jednoczesny pomiar ciśnienia tętniczego na obu kończynach — diagnostyka różnic ciśnień i zwężeń tętnic. Elkardia, Lublin.",
    heroBody: "Jednoczesny pomiar ciśnienia na obu ramionach — wykrywa różnice, które wskazują na zwężenie tętnicy i podnoszą ryzyko sercowo-naczyniowe.",
    duration: "ok. 15 minut",
    what: {
      heading: "Na czym polega symultaniczny pomiar?",
      body: "Ciśnienie mierzone kolejno na jednej, a potem drugiej ręce daje wyniki trudne do porównania — wartości zmieniają się z minuty na minutę pod wpływem oddechu, emocji czy pozycji. Pomiar symultaniczny wykonujemy dwoma aparatami jednocześnie, dzięki czemu obie wartości pochodzą z dokładnie tego samego momentu i można je rzetelnie zestawić. Istotna różnica między kończynami sugeruje zwężenie tętnicy podobojczykowej lub inną patologię naczyniową i sama w sobie jest markerem podwyższonego ryzyka sercowo-naczyniowego.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent siada wygodnie i odpoczywa kilka minut, ponieważ pomiar wykonany zaraz po wejściu do gabinetu byłby niemiarodajny. Następnie zakładamy mankiety na oba ramiona i uruchamiamy oba aparaty równocześnie. Pomiar powtarzamy zwykle dwu- lub trzykrotnie, aby wykluczyć przypadkowe wahania. Wynik wraz z wyliczoną różnicą między kończynami lekarz interpretuje w kontekście pozostałych badań — przy istotnej różnicy zwykle poszerzamy diagnostykę o USG Doppler tętnic.",
    },
    prep: [
      "Kilka minut odpoczynku przed pomiarem",
      "Luźna koszula umożliwiająca odsłonięcie obu ramion",
      "Bez kawy i papierosów na godzinę przed badaniem",
      "Informacja o przyjętych tego dnia lekach",
    ],
    indications: [
      "Podejrzenie zwężenia tętnicy podobojczykowej",
      "Zauważona różnica ciśnień między rękami",
      "Diagnostyka miażdżycy i oceny ryzyka naczyniowego",
      "Nadciśnienie trudne do kontroli",
    ],
  },
  {
    slug: "kontrola-stymulatora-serca",
    title: "Kontrola stymulatora serca",
    cat: "Kardiologiczne",
    metaTitle: "Kontrola stymulatora serca Lublin — Elkardia",
    metaDescription: "Okresowa kontrola rozrusznika serca — ocena baterii, elektrod i optymalizacja parametrów stymulacji. Elkardia, Lublin.",
    heroBody: "Okresowa kontrola rozrusznika — sprawdzenie stanu baterii i elektrod oraz dostrojenie parametrów stymulacji do aktualnych potrzeb pacjenta.",
    duration: "ok. 20–30 minut",
    what: {
      heading: "Po co kontrolować stymulator?",
      body: "Wszczepiony stymulator wymaga regularnych kontroli, zwykle co 6–12 miesięcy. Podczas wizyty sprawdzamy stan baterii i szacujemy pozostały czas jej pracy, oceniamy parametry elektryczne elektrod oraz odczytujemy pamięć urządzenia — w tym zarejestrowane epizody arytmii, o których pacjent często nie wie. Kontrola pozwala też dostroić ustawienia do aktualnych potrzeb: zmienić progi stymulacji, zoptymalizować zużycie energii i wydłużyć żywotność baterii. To badanie nieinwazyjne i bezbolesne.",
    },
    how: {
      heading: "Jak przebiega kontrola?",
      body: "Pacjent kładzie się lub siada wygodnie, a technik przykłada głowicę programatora do skóry nad urządzeniem — bezprzewodowa komunikacja nie wymaga żadnego nakłucia. Programator odczytuje pamięć stymulatora i wykonuje serię testów elektrycznych. Podczas testów pacjent może przez chwilę poczuć zmianę rytmu serca, co jest normalne i całkowicie bezpieczne. Lekarz analizuje odczytane dane, w razie potrzeby modyfikuje ustawienia i ustala termin kolejnej kontroli. Wynik wraz z parametrami trafia do książeczki stymulatora.",
    },
    prep: [
      "Książeczka stymulatora — konieczna na każdej kontroli",
      "Lista aktualnie przyjmowanych leków",
      "Informacja o zasłabnięciach lub kołataniach od ostatniej wizyty",
      "Badanie nie wymaga bycia na czczo",
    ],
    indications: [
      "Rutynowa kontrola co 6–12 miesięcy",
      "Zasłabnięcia lub kołatania u pacjenta ze stymulatorem",
      "Podejrzenie wyczerpywania się baterii",
      "Ocena epizodów arytmii zapisanych w pamięci urządzenia",
    ],
  },
  {
    slug: "kontrola-kardiowertera-icd",
    title: "Kontrola kardiowertera (ICD)",
    cat: "Kardiologiczne",
    metaTitle: "Kontrola kardiowertera-defibrylatora ICD Lublin — Elkardia",
    metaDescription: "Kontrola wszczepialnego kardiowertera-defibrylatora (ICD) — odczyt interwencji, ocena elektrod i optymalizacja stref terapii. Elkardia, Lublin.",
    heroBody: "Kontrola wszczepionego defibrylatora — odczyt wszystkich interwencji urządzenia i dostrojenie stref terapii, by uniknąć nieadekwatnych wyładowań.",
    duration: "ok. 30 minut",
    what: {
      heading: "Na czym polega kontrola ICD?",
      body: "Kardiowerter-defibrylator nie tylko stymuluje serce, ale przede wszystkim przerywa groźne arytmie komorowe — stymulacją antyarytmiczną albo wyładowaniem. Kontrola obejmuje więc wszystko to, co przy zwykłym stymulatorze, a dodatkowo szczegółową analizę zarejestrowanych epizodów i wykonanych interwencji. Kluczowe jest odróżnienie wyładowań uzasadnionych od nieadekwatnych, wywołanych na przykład szybkim migotaniem przedsionków. Właściwe zaprogramowanie stref terapii pozwala znacząco ograniczyć liczbę niepotrzebnych wyładowań, które są dla pacjenta bardzo obciążające.",
    },
    how: {
      heading: "Jak przebiega kontrola?",
      body: "Przebieg jest podobny jak przy stymulatorze — głowica programatora przyłożona do skóry nad urządzeniem nawiązuje łączność i odczytuje pamięć. Analizujemy każdy zarejestrowany epizod arytmii wraz z zapisem wewnątrzsercowym, oceniając zasadność reakcji urządzenia. Sprawdzamy parametry elektrod i stan baterii, a następnie w razie potrzeby modyfikujemy strefy detekcji i terapii. Rutynowa kontrola nie wymaga wyzwalania wyładowania. Wynik dokumentujemy w książeczce i ustalamy termin kolejnej wizyty.",
    },
    prep: [
      "Książeczka urządzenia — konieczna na każdej kontroli",
      "Dokładna informacja o wszystkich odczutych wyładowaniach i ich okolicznościach",
      "Lista aktualnie przyjmowanych leków",
      "Badanie nie wymaga bycia na czczo",
    ],
    indications: [
      "Rutynowa kontrola co 3–6 miesięcy",
      "Po każdym odczutym wyładowaniu urządzenia",
      "Podejrzenie nieadekwatnych interwencji",
      "Ocena i optymalizacja stref terapii",
      "Podejrzenie uszkodzenia elektrody",
    ],
  },
  {
    slug: "badanie-elektrofizjologiczne",
    title: "Badanie elektrofizjologiczne",
    cat: "Kardiologiczne",
    metaTitle: "Badanie elektrofizjologiczne (EPS) Lublin — Elkardia",
    metaDescription: "Inwazyjne badanie elektrofizjologiczne serca (EPS) — precyzyjne rozpoznanie mechanizmu arytmii i kwalifikacja do ablacji. Elkardia, Lublin.",
    heroBody: "Inwazyjne badanie układu elektrycznego serca — ustala mechanizm arytmii i wskazuje jej dokładne źródło, często bezpośrednio przed ablacją.",
    duration: "ok. 1–2 godziny",
    what: {
      heading: "Czym jest badanie elektrofizjologiczne?",
      body: "Badanie elektrofizjologiczne, w skrócie EPS, to inwazyjna ocena układu elektrycznego serca wykonywana za pomocą cewników wprowadzonych przez żyły udowe. Pozwala rozpoznać mechanizm arytmii, którego nie da się ustalić na podstawie samego EKG — na przykład odróżnić poszczególne typy częstoskurczów nadkomorowych. Bardzo często EPS wykonujemy w tym samym zabiegu co ablację: najpierw ustalamy dokładne źródło i mechanizm arytmii, a następnie od razu je eliminujemy.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent otrzymuje sedację, a elektrofizjolog nakłuwa żyłę udową w znieczuleniu miejscowym i wprowadza cienkie cewniki diagnostyczne do jam serca. Cewniki rejestrują sygnały elektryczne bezpośrednio z wnętrza serca, znacznie dokładniej niż EKG z powierzchni ciała. Następnie wykonujemy stymulację programowaną — kontrolowane pobudzenia mające na celu wywołanie arytmii w bezpiecznych warunkach pracowni, co pozwala rozpoznać jej mechanizm. Jeżeli stwierdzimy wskazania, w tej samej sesji przechodzimy do ablacji.",
    },
    prep: [
      "Na czczo — co najmniej 6 godzin przed zabiegiem",
      "Aktualne wyniki badań krwi i grupa krwi",
      "Ustalenie z lekarzem odstawienia leków przeciwkrzepliwych i antyarytmicznych",
      "Transport do domu — po sedacji nie wolno prowadzić pojazdów",
      "Hospitalizacja zwykle 1 dzień",
    ],
    indications: [
      "Częstoskurcze nadkomorowe wymagające rozpoznania mechanizmu",
      "Kwalifikacja do ablacji",
      "Zespół WPW i podejrzenie dróg dodatkowych",
      "Omdlenia o podejrzeniu przyczyny arytmicznej",
      "Ocena ryzyka nagłego zgonu sercowego",
    ],
  },

  // ── Pediatryczne ──
  {
    slug: "ekg-dzieci",
    title: "EKG dzieci",
    cat: "Pediatryczne",
    metaTitle: "EKG dla dzieci Lublin — Elkardia",
    metaDescription: "EKG spoczynkowe u dzieci — bezbolesne badanie rytmu serca w przyjaznych warunkach. Kardiologia dziecięca w Elkardii, Lublin.",
    heroBody: "Bezbolesne, kilkuminutowe badanie rytmu serca dziecka — podstawowy element diagnostyki kardiologicznej i kwalifikacji do sportu.",
    duration: "ok. 10 minut",
    what: {
      heading: "Czym jest EKG u dziecka?",
      body: "EKG rejestruje czynność elektryczną serca za pomocą elektrod przyklejanych do skóry. Badanie jest całkowicie bezbolesne i nieinwazyjne — urządzenie tylko odbiera sygnały, nie przepływa przez ciało żaden prąd, o czym warto uprzedzić dziecko. Zapis pozwala ocenić rytm i częstość pracy serca oraz wykryć zaburzenia przewodzenia i cechy przerostu. Interpretacja EKG dziecięcego rządzi się własnymi normami, które zmieniają się wraz z wiekiem — dlatego opisuje je kardiolog dziecięcy, a nie lekarz dorosłych.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Dziecko rozbiera się do pasa i kładzie na kozetce. Przyklejamy kilka elektrod na klatce piersiowej, nadgarstkach i kostkach, a sam zapis trwa kilkanaście sekund — warunkiem dobrej jakości jest spokojne leżenie bez ruchu przez ten krótki moment. Rodzic zostaje przy dziecku przez cały czas. U najmłodszych badanie wykonujemy w tempie dostosowanym do współpracy, czasem w kilku podejściach. Po zdjęciu elektrod dziecko od razu może się ubrać, a wynik omawiamy tego samego dnia.",
    },
    prep: [
      "Badanie nie wymaga bycia na czczo",
      "Ubranie łatwe do zdjęcia — najlepiej dwuczęściowe",
      "Warto uprzedzić dziecko, że badanie nie boli i nie kłuje",
      "Dokumentacja z wcześniejszych badań kardiologicznych",
    ],
    indications: [
      "Szmer nad sercem stwierdzony przez pediatrę",
      "Kołatania serca, zasłabnięcia, omdlenia",
      "Kwalifikacja do uprawiania sportu",
      "Ból w klatce piersiowej u dziecka",
      "Obciążający wywiad rodzinny",
    ],
  },
  {
    slug: "echo-serca-dzieci",
    title: "Echo serca dzieci",
    cat: "Pediatryczne",
    metaTitle: "Echo serca dla dzieci Lublin — Elkardia",
    metaDescription: "Echokardiografia dziecięca — bezbolesne USG serca oceniające budowę i pracę serca oraz wady wrodzone. Elkardia, Lublin.",
    heroBody: "USG serca dziecka — bezbolesne badanie oceniające budowę serca i przepływy, podstawowe narzędzie w diagnostyce wad wrodzonych.",
    duration: "ok. 30 minut",
    what: {
      heading: "Czym jest echo serca u dziecka?",
      body: "Echokardiografia to badanie ultrasonograficzne serca — obraz powstaje dzięki falom dźwiękowym, bez żadnego promieniowania, dlatego można je bezpiecznie powtarzać dowolnie często. U dzieci echo jest podstawowym narzędziem rozpoznawania i monitorowania wad wrodzonych. Pozwala ocenić budowę wszystkich jam i zastawek, kierunek oraz prędkość przepływów, a także kurczliwość mięśnia sercowego. Bardzo często to właśnie echo rozstrzyga, czy usłyszany przez pediatrę szmer jest niewinny, czy wymaga dalszego postępowania.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Dziecko kładzie się na kozetce, rozebrane do pasa. Lekarz nakłada na klatkę piersiową żel — jedyna niedogodność badania, bo bywa chłodny — i przesuwa po niej głowicę, obserwując serce z różnych projekcji. Badanie jest bezbolesne, a rodzic pozostaje przy dziecku przez cały czas. W trakcie słychać charakterystyczny dźwięk przepływu krwi, co dla wielu dzieci jest najciekawszym momentem wizyty. U niemowląt badanie często wykonujemy podczas karmienia lub snu.",
    },
    prep: [
      "Badanie nie wymaga bycia na czczo",
      "Ubranie łatwe do zdjęcia",
      "Niemowlęta: warto zabrać butelkę lub smoczek",
      "Wyniki poprzednich badań echo, jeśli były wykonywane",
    ],
    indications: [
      "Szmer nad sercem",
      "Podejrzenie lub monitorowanie wrodzonej wady serca",
      "Zaburzenia rozwoju i przyrostu masy ciała u niemowlęcia",
      "Sinica, duszność, męczliwość",
      "Kwalifikacja do sportu wyczynowego",
    ],
  },
  {
    slug: "holter-ekg-dzieci-24h",
    title: "Holter EKG dzieci 24h",
    cat: "Pediatryczne",
    metaTitle: "Holter EKG dla dzieci 24h Lublin — Elkardia",
    metaDescription: "Całodobowe monitorowanie EKG u dzieci — rejestracja rytmu serca podczas zwykłej aktywności dziecka. Elkardia, Lublin.",
    heroBody: "Całodobowy zapis pracy serca dziecka podczas normalnej aktywności — wychwytuje arytmie niewidoczne w krótkim badaniu EKG.",
    duration: "24 godziny rejestracji",
    what: {
      heading: "Czym jest Holter EKG u dziecka?",
      body: "Holter to niewielki rejestrator noszony przez dobę, zapisujący każde uderzenie serca. U dzieci sprawdza się szczególnie dobrze, bo objawy takie jak kołatania czy zasłabnięcia pojawiają się zwykle w trakcie zabawy lub wysiłku — a więc dokładnie wtedy, gdy nie ma możliwości wykonania zwykłego EKG. Całodobowy zapis pozwala powiązać zgłaszany przez dziecko objaw z rzeczywistym zapisem z tego samego momentu. Rejestratory dziecięce są lekkie i małe, więc nie przeszkadzają w normalnej aktywności.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Przyklejamy kilka elektrod na klatce piersiowej dziecka i mocujemy rejestrator w małej saszetce noszonej przez dobę. Dziecko wraca do domu, idzie do przedszkola lub szkoły i bawi się normalnie — to warunek wiarygodności badania, dlatego prosimy, by go nie ograniczać. Rodzic prowadzi dzienniczek, notując godziny snu, zabawy i wszelkich zgłaszanych objawów. Po dobie wracacie do pracowni, gdzie zdejmujemy urządzenie, a kardiolog dziecięcy analizuje pełny zapis i zestawia go z dzienniczkiem.",
    },
    prep: [
      "Kąpiel przed założeniem — w trakcie badania nie można się kąpać",
      "Bawełniana koszulka i ubranie na zmianę",
      "Prowadzenie dzienniczka przez rodzica",
      "Warto uprzedzić dziecko, że urządzenia nie wolno zdejmować",
    ],
    indications: [
      "Kołatania serca zgłaszane przez dziecko",
      "Zasłabnięcia i omdlenia",
      "Nieregularny rytm stwierdzony w EKG",
      "Ocena leczenia antyarytmicznego",
      "Monitorowanie po operacji kardiochirurgicznej",
    ],
  },
  {
    slug: "holter-cisnieniowy-rr-dzieci",
    title: "Holter ciśnieniowy RR dzieci",
    cat: "Pediatryczne",
    metaTitle: "Holter ciśnieniowy RR dla dzieci Lublin — Elkardia",
    metaDescription: "Całodobowy pomiar ciśnienia tętniczego u dzieci (ABPM) — rozpoznanie nadciśnienia według norm pediatrycznych. Elkardia, Lublin.",
    heroBody: "Całodobowy automatyczny pomiar ciśnienia u dziecka — jedyna wiarygodna metoda rozpoznania nadciśnienia w wieku rozwojowym.",
    duration: "24 godziny rejestracji",
    what: {
      heading: "Po co mierzyć dziecku ciśnienie przez dobę?",
      body: "Nadciśnienie u dzieci bywa niedoceniane, a jego rozpoznanie jest trudniejsze niż u dorosłych — normy zależą od wieku, płci i wzrostu dziecka, więc tej samej wartości nie da się ocenić bez odniesienia do siatek centylowych. Do tego pomiar w gabinecie jest u dzieci wyjątkowo zawodny, bo sama wizyta u lekarza często podnosi ciśnienie. Całodobowa rejestracja w warunkach domowych i szkolnych daje obraz nieporównanie bardziej wiarygodny i pozwala ocenić nocny profil ciśnienia.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Na ramię dziecka zakładamy mankiet w rozmiarze dobranym do obwodu ramienia — właściwy dobór mankietu jest kluczowy, bo zbyt duży lub zbyt mały zafałszuje wynik. Mankiet łączymy z niewielkim aparatem noszonym w saszetce. Urządzenie samo mierzy ciśnienie co 15–30 minut w dzień i rzadziej w nocy. Dziecko powinno na czas pomiaru rozluźnić rękę i nie ruszać się przez kilkanaście sekund. Rodzic prowadzi dzienniczek. Po dobie generujemy raport odniesiony do norm pediatrycznych.",
    },
    prep: [
      "Luźna koszulka z szerokim rękawem",
      "Wyjaśnienie dziecku, że mankiet ściska rękę, ale nie boli",
      "Notowanie godzin snu i aktywności",
      "Aktualny pomiar wzrostu i masy ciała — potrzebny do interpretacji",
    ],
    indications: [
      "Podwyższone ciśnienie stwierdzone przez pediatrę",
      "Otyłość i nadwaga u dziecka",
      "Choroby nerek",
      "Obciążający wywiad rodzinny w kierunku nadciśnienia",
      "Ocena skuteczności leczenia hipotensyjnego",
    ],
  },
  {
    slug: "monitorowanie-saturacji-24h",
    title: "Monitorowanie saturacji 24h",
    cat: "Pediatryczne",
    metaTitle: "Całodobowe monitorowanie saturacji u dzieci Lublin — Elkardia",
    metaDescription: "Całodobowy pomiar wysycenia krwi tlenem u dzieci — diagnostyka desaturacji nocnych i zaburzeń oddychania. Elkardia, Lublin.",
    heroBody: "Całodobowy pomiar wysycenia krwi tlenem — wykrywa spadki saturacji pojawiające się głównie w nocy, poza obserwacją rodzica.",
    duration: "24 godziny rejestracji",
    what: {
      heading: "Czym jest całodobowa pulsoksymetria?",
      body: "Pulsoksymetria mierzy wysycenie hemoglobiny tlenem za pomocą czujnika nakładanego na palec lub stopę — bez nakłuwania i bez bólu. Pojedynczy pomiar w gabinecie pokazuje tylko jedną chwilę, tymczasem u dzieci istotne spadki saturacji występują najczęściej w nocy, podczas snu, gdy nikt ich nie obserwuje. Zapis całodobowy rejestruje te epizody wraz z ich liczbą, czasem trwania i głębokością, co pozwala ocenić, czy mamy do czynienia z istotnym problemem oddechowym lub sercowym.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Na palec dziecka zakładamy miękki czujnik połączony z niewielkim rejestratorem, mocowanym tak, by nie przeszkadzał w zabawie ani we śnie. Dziecko wraca do domu i funkcjonuje normalnie — kluczowa jest zwłaszcza noc spędzona we własnym łóżku i zwykłym rytmie. Rodzic prowadzi dzienniczek, notując porę zasypiania, chrapanie, bezdechy czy niepokój w nocy. Po dobie oddajecie urządzenie, a lekarz analizuje przebieg saturacji, zwracając uwagę na liczbę i głębokość desaturacji.",
    },
    prep: [
      "Kąpiel przed założeniem czujnika",
      "Bez lakieru na paznokciach — zaburza odczyt czujnika",
      "Notowanie chrapania, bezdechów i niepokoju nocnego",
      "Zachowanie zwykłego rytmu snu",
    ],
    indications: [
      "Chrapanie i podejrzenie bezdechu sennego u dziecka",
      "Sinica lub epizody zasinienia",
      "Wrodzona wada serca — monitorowanie utlenowania",
      "Przewlekłe choroby układu oddechowego",
      "Niepokój i wybudzenia nocne o niejasnej przyczynie",
    ],
  },

  // ── USG / Doppler ──
  {
    slug: "usg-tarczycy",
    title: "USG tarczycy",
    cat: "USG / Doppler",
    metaTitle: "USG tarczycy Lublin — Elkardia",
    metaDescription: "USG tarczycy — ocena wielkości gruczołu, guzków i węzłów chłonnych szyi w klasyfikacji EU-TIRADS. Elkardia, Lublin.",
    heroBody: "Ultrasonograficzna ocena tarczycy — wykrywa guzki, mierzy objętość gruczołu i klasyfikuje zmiany według skali EU-TIRADS.",
    duration: "ok. 15–20 minut",
    what: {
      heading: "Czym jest USG tarczycy?",
      body: "USG tarczycy to bezbolesne badanie obrazowe oceniające gruczoł tarczowy oraz okoliczne węzły chłonne szyi. Pozwala zmierzyć objętość tarczycy, ocenić jej strukturę i echogeniczność oraz wykryć guzki — także te niewyczuwalne ręką, o średnicy kilku milimetrów. Każdą zmianę ogniskową opisujemy w standaryzowanej skali ryzyka EU-TIRADS, która porządkuje dalsze postępowanie i wskazuje, czy guzek wymaga biopsji, czy tylko obserwacji. Badanie nie wykorzystuje promieniowania i można je bezpiecznie powtarzać.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent kładzie się na plecach z lekko odchyloną do tyłu głową — pod kark podkładamy wałek, co eksponuje szyję i ułatwia dostęp głowicy. Lekarz nakłada żel i przesuwa głowicę po szyi, obrazując oba płaty i cieśń tarczycy, a następnie oceniając węzły chłonne. W trakcie badania możemy poprosić o przełknięcie śliny, co uwidacznia ruchomość gruczołu. Badanie jest bezbolesne, choć ucisk głowicy bywa lekko odczuwalny. Opis wraz z klasyfikacją EU-TIRADS otrzymujecie tego samego dnia.",
    },
    prep: [
      "Badanie nie wymaga żadnego przygotowania ani bycia na czczo",
      "Odzież z dekoltem umożliwiającym odsłonięcie szyi",
      "Zdjęcie łańcuszków i naszyjników",
      "Wyniki wcześniejszych USG tarczycy oraz badań hormonalnych",
    ],
    indications: [
      "Wyczuwalny guzek lub powiększenie tarczycy",
      "Nieprawidłowe wyniki TSH, fT3, fT4",
      "Choroba Hashimoto lub Gravesa-Basedowa",
      "Monitorowanie znanych guzków tarczycy",
      "Powiększone węzły chłonne szyi",
    ],
  },
  {
    slug: "usg-piersi",
    title: "USG piersi",
    cat: "USG / Doppler",
    metaTitle: "USG piersi Lublin — Elkardia",
    metaDescription: "USG piersi — badanie obrazowe gruczołów piersiowych i węzłów chłonnych pach, opis w klasyfikacji BI-RADS. Elkardia, Lublin.",
    heroBody: "Ultrasonograficzna ocena gruczołów piersiowych i węzłów chłonnych pach — badanie z wyboru u kobiet młodszych, o gęstej strukturze piersi.",
    duration: "ok. 20 minut",
    what: {
      heading: "Czym jest USG piersi?",
      body: "USG piersi ocenia strukturę gruczołów piersiowych oraz węzły chłonne dołów pachowych. U kobiet przed 40. rokiem życia jest badaniem z wyboru, ponieważ młoda pierś ma gęstą budowę gruczołową, w której mammografia jest mało czytelna — ultrasonografia radzi sobie z taką strukturą znacznie lepiej. Badanie dobrze różnicuje zmiany lite od torbieli i pozwala ocenić ich unaczynienie. Każdą zmianę opisujemy w standaryzowanej skali BI-RADS, która jednoznacznie określa dalsze postępowanie.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjentka rozbiera się do pasa i kładzie na plecach z rękami uniesionymi za głowę — taka pozycja rozprowadza tkankę gruczołową i poprawia jakość obrazu. Lekarz nakłada żel i systematycznie bada obie piersi głowicą, sektor po sektorze, a następnie oceniania doły pachowe. Badanie jest bezbolesne, choć w okolicach zmienionych zapalnie ucisk bywa nieprzyjemny. Opis w klasyfikacji BI-RADS otrzymujecie tego samego dnia wraz z zaleceniem dotyczącym dalszego postępowania.",
    },
    prep: [
      "Optymalny termin: pierwsza połowa cyklu, między 5. a 12. dniem",
      "Bez balsamów i olejków na skórze piersi w dniu badania",
      "Dwuczęściowe ubranie ułatwiające rozebranie się do pasa",
      "Wyniki wcześniejszych USG i mammografii — do porównania",
    ],
    indications: [
      "Wyczuwalny guzek w piersi",
      "Ból, wyciek z brodawki, zmiany skórne",
      "Badanie profilaktyczne u kobiet poniżej 40. roku życia",
      "Uzupełnienie mammografii przy gęstej strukturze piersi",
      "Monitorowanie znanych zmian łagodnych",
    ],
  },
  {
    slug: "usg-jamy-brzusznej",
    title: "USG jamy brzusznej",
    cat: "USG / Doppler",
    metaTitle: "USG jamy brzusznej Lublin — Elkardia",
    metaDescription: "USG jamy brzusznej — kompleksowa ocena wątroby, pęcherzyka, trzustki, nerek, śledziony i aorty. Elkardia, Lublin.",
    heroBody: "Kompleksowa ocena narządów jamy brzusznej — wątroby, pęcherzyka żółciowego, trzustki, nerek, śledziony i aorty w jednym badaniu.",
    duration: "ok. 20–30 minut",
    what: {
      heading: "Co obejmuje USG jamy brzusznej?",
      body: "To najczęściej wykonywane badanie ultrasonograficzne, obejmujące wątrobę, pęcherzyk żółciowy i drogi żółciowe, trzustkę, śledzionę, nerki, nadnercza, pęcherz moczowy oraz aortę brzuszną. Pozwala wykryć kamicę żółciową i nerkową, stłuszczenie wątroby, torbiele i guzy, wodonercze czy tętniaka aorty brzusznej. Dla kardiologa szczególnie istotna jest ocena aorty i wątroby — powiększona, zastoinowa wątroba bywa pierwszym uchwytnym objawem niewydolności prawokomorowej serca.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent kładzie się na plecach z odsłoniętym brzuchem. Lekarz nakłada żel i przesuwa głowicę, oceniając kolejne narządy z różnych ustawień. W trakcie badania prosimy o głębokie wdechy i wstrzymanie oddechu — przepona spycha wtedy wątrobę w dół, co znacznie poprawia jej widoczność. Czasem prosimy też o obrócenie się na bok. Badanie jest bezbolesne, choć w miejscach zapalnie zmienionych ucisk głowicy może być tkliwy — co samo w sobie bywa cenną informacją diagnostyczną.",
    },
    prep: [
      "Na czczo — co najmniej 6 godzin bez jedzenia",
      "Pęcherz moczowy wypełniony: ok. 1 litr niegazowanej wody na godzinę przed badaniem",
      "Dzień wcześniej dieta lekkostrawna, bez warzyw wzdymających i napojów gazowanych",
      "Leki przyjmujemy normalnie, popijając niewielką ilością wody",
    ],
    indications: [
      "Bóle brzucha o niejasnej przyczynie",
      "Podejrzenie kamicy żółciowej lub nerkowej",
      "Nieprawidłowe próby wątrobowe",
      "Badanie przesiewowe w kierunku tętniaka aorty brzusznej",
      "Ocena zastoju w niewydolności serca",
    ],
  },
  {
    slug: "usg-slinianek",
    title: "USG ślinianek",
    cat: "USG / Doppler",
    metaTitle: "USG ślinianek Lublin — Elkardia",
    metaDescription: "USG gruczołów ślinowych — ocena ślinianek przyusznych i podżuchwowych, diagnostyka kamicy i zmian ogniskowych. Elkardia, Lublin.",
    heroBody: "Ocena ślinianek przyusznych i podżuchwowych — diagnostyka bolesnych obrzęków, kamicy przewodów i guzów gruczołów ślinowych.",
    duration: "ok. 15 minut",
    what: {
      heading: "Czym jest USG ślinianek?",
      body: "Badanie obejmuje ślinianki przyuszne i podżuchwowe wraz z otaczającymi węzłami chłonnymi. Najczęstszym powodem jego wykonania jest bolesny obrzęk twarzy nasilający się podczas jedzenia — objaw typowy dla kamicy przewodu ślinianki, gdy złóg blokuje odpływ śliny. USG dobrze uwidacznia takie złogi i poszerzone przewody, a także pozwala różnicować stany zapalne od zmian ogniskowych. Badanie jest szybkie, bezbolesne i nie wymaga żadnego przygotowania.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent kładzie się na plecach z głową odchyloną i obróconą na bok, co eksponuje okolicę przyuszną i podżuchwową. Lekarz nakłada żel i bada obie strony, porównując je ze sobą — symetria jest tu istotną wskazówką. Ocenia wielkość i strukturę gruczołów, szerokość przewodów wyprowadzających oraz obecność złogów i zmian ogniskowych, a na koniec okoliczne węzły chłonne. Czasem prosimy o zassanie plasterka cytryny, co pobudza wydzielanie śliny i uwidacznia przewody.",
    },
    prep: [
      "Badanie nie wymaga żadnego przygotowania",
      "Można jeść i pić normalnie",
      "Odzież umożliwiająca odsłonięcie szyi",
      "Zdjęcie kolczyków i łańcuszków",
    ],
    indications: [
      "Bolesny obrzęk twarzy nasilający się przy jedzeniu",
      "Podejrzenie kamicy ślinianki",
      "Wyczuwalny guzek w okolicy przyusznej lub podżuchwowej",
      "Nawracające stany zapalne ślinianek",
      "Suchość w jamie ustnej, podejrzenie zespołu Sjögrena",
    ],
  },
  {
    slug: "usg-ukladu-moczowego",
    title: "USG układu moczowego",
    cat: "USG / Doppler",
    metaTitle: "USG układu moczowego Lublin — Elkardia",
    metaDescription: "USG nerek, moczowodów i pęcherza moczowego — diagnostyka kamicy, wodonercza i zalegania moczu. Elkardia, Lublin.",
    heroBody: "Ocena nerek, moczowodów i pęcherza moczowego — diagnostyka kamicy, wodonercza i zalegania moczu po mikcji.",
    duration: "ok. 20 minut",
    what: {
      heading: "Co obejmuje USG układu moczowego?",
      body: "Badanie ocenia obie nerki, moczowody oraz pęcherz moczowy. Pozwala wykryć kamicę, wodonercze, torbiele i guzy nerek, a także ocenić grubość ściany pęcherza i zaleganie moczu po mikcji. To badanie pierwszego wyboru przy kolce nerkowej i przy nawracających zakażeniach układu moczowego. U pacjentów kardiologicznych ma dodatkowe znaczenie: nerki i serce są ze sobą ściśle powiązane, a ocena nerek jest istotna przy nadciśnieniu tętniczym i przed włączeniem części leków.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Badanie zaczynamy przy wypełnionym pęcherzu — to warunek jego oceny, bo pusty pęcherz jest praktycznie niewidoczny w USG. Pacjent kładzie się na plecach, lekarz nakłada żel i ocenia kolejno nerki, prosząc czasem o obrót na bok lub głęboki wdech. Następnie obrazuje wypełniony pęcherz. Na koniec prosimy o oddanie moczu i powtarzamy pomiar, by ocenić zaleganie po mikcji — ten prosty parametr bywa kluczowy w diagnostyce przeszkody podpęcherzowej.",
    },
    prep: [
      "Pęcherz wypełniony: ok. 1 litr niegazowanej wody na godzinę przed badaniem",
      "Nie oddawać moczu bezpośrednio przed badaniem",
      "Dzień wcześniej dieta lekkostrawna, bez napojów gazowanych",
      "Wyniki badania ogólnego moczu i kreatyniny, jeśli są dostępne",
    ],
    indications: [
      "Kolka nerkowa i podejrzenie kamicy",
      "Nawracające zakażenia układu moczowego",
      "Krwiomocz",
      "Nadciśnienie tętnicze — ocena nerek",
      "Podwyższona kreatynina, ocena przed leczeniem",
    ],
  },
  {
    slug: "usg-prostaty",
    title: "USG prostaty",
    cat: "USG / Doppler",
    metaTitle: "USG prostaty Lublin — Elkardia",
    metaDescription: "USG gruczołu krokowego — ocena wielkości prostaty i zalegania moczu po mikcji. Elkardia, Lublin.",
    heroBody: "Ocena wielkości i struktury gruczołu krokowego wraz z pomiarem zalegania moczu — badanie przezbrzuszne, bezbolesne.",
    duration: "ok. 15 minut",
    what: {
      heading: "Czym jest USG prostaty?",
      body: "Wykonujemy badanie przezbrzuszne, przez powłoki podbrzusza, przy wypełnionym pęcherzu moczowym — pełny pęcherz tworzy okno akustyczne, przez które widać leżący pod nim gruczoł krokowy. Badanie pozwala zmierzyć objętość prostaty, ocenić jej zarys i strukturę oraz zmierzyć zaleganie moczu po mikcji. Jest bezbolesne i nieinwazyjne. Przy podejrzeniu zmian ogniskowych wymagających dokładniejszej oceny wskazane bywa badanie przezodbytnicze (TRUS), o czym poinformuje lekarz.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent zgłasza się z wypełnionym pęcherzem i kładzie na plecach z odsłoniętym podbrzuszem. Lekarz nakłada żel i przykłada głowicę nad spojeniem łonowym, kierując wiązkę przez pełny pęcherz na prostatę. Mierzy wymiary gruczołu i wylicza jego objętość, ocenia zarys i strukturę oraz sprawdza ścianę pęcherza pod kątem cech przeciążenia. Na koniec prosimy o oddanie moczu i powtarzamy pomiar, oceniając zaleganie — parametr kluczowy przy przeroście prostaty.",
    },
    prep: [
      "Pęcherz wypełniony: ok. 1 litr niegazowanej wody na godzinę przed badaniem",
      "Nie oddawać moczu bezpośrednio przed badaniem",
      "Wynik PSA, jeśli był oznaczany",
      "Dzień wcześniej dieta lekkostrawna",
    ],
    indications: [
      "Objawy przeszkody podpęcherzowej — słaby strumień, częstomocz nocny",
      "Podejrzenie łagodnego przerostu prostaty",
      "Podwyższone PSA",
      "Zaleganie moczu po mikcji",
      "Nawracające zakażenia układu moczowego u mężczyzn",
    ],
  },
  {
    slug: "usg-jader",
    title: "USG jąder",
    cat: "USG / Doppler",
    metaTitle: "USG jąder Lublin — Elkardia",
    metaDescription: "USG jąder i moszny — diagnostyka guzów, wodniaka, żylaków powrózka i stanów zapalnych. Elkardia, Lublin.",
    heroBody: "Ocena jąder, najądrzy i zawartości moszny — diagnostyka guzów, wodniaka, żylaków powrózka nasiennego i stanów zapalnych.",
    duration: "ok. 15–20 minut",
    what: {
      heading: "Czym jest USG jąder?",
      body: "Badanie obejmuje jądra, najądrza i całą zawartość moszny, uzupełnione oceną przepływów w opcji Dopplera. Jest podstawowym narzędziem w diagnostyce każdej wyczuwalnej zmiany w mosznie — pozwala odróżnić niegroźnego wodniaka czy torbiel najądrza od zmiany litej wymagającej pilnej konsultacji urologicznej. Doppler ma tu szczególne znaczenie: ocena unaczynienia różnicuje zapalenie od skrętu jądra, który jest stanem nagłym wymagającym operacji w ciągu kilku godzin.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent kładzie się na plecach, a mosznę podpieramy ręcznikiem dla stabilizacji i wygody. Lekarz nakłada ciepły żel i bada obie strony głowicą o wysokiej częstotliwości, zawsze porównawczo — jądro zdrowe stanowi punkt odniesienia dla zmienionego. Następnie włącza Doppler i ocenia unaczynienie. Przy podejrzeniu żylaków prosimy o wykonanie próby Valsalvy, czyli parcia przy zamkniętych ustach, co uwidacznia poszerzone żyły. Badanie jest bezbolesne poza obszarami zapalnymi.",
    },
    prep: [
      "Badanie nie wymaga żadnego przygotowania",
      "Zalecana higiena okolicy przed wizytą",
      "Dwuczęściowe ubranie",
      "W razie ostrego, nagłego bólu — badanie wykonujemy pilnie, bez odkładania",
    ],
    indications: [
      "Wyczuwalny guzek lub zgrubienie w mosznie",
      "Ból i obrzęk moszny",
      "Podejrzenie żylaków powrózka nasiennego",
      "Diagnostyka niepłodności męskiej",
      "Podejrzenie wodniaka jądra",
    ],
  },
  {
    slug: "usg-wezlow-chlonnych",
    title: "USG węzłów chłonnych",
    cat: "USG / Doppler",
    metaTitle: "USG węzłów chłonnych Lublin — Elkardia",
    metaDescription: "USG węzłów chłonnych szyi, pach i pachwin — różnicowanie zmian odczynowych i podejrzanych. Elkardia, Lublin.",
    heroBody: "Ocena węzłów chłonnych szyi, pach i pachwin — różnicuje powiększenie odczynowe od zmian wymagających dalszej diagnostyki.",
    duration: "ok. 15–20 minut",
    what: {
      heading: "Czym jest USG węzłów chłonnych?",
      body: "Badanie ocenia węzły chłonne w dostępnych ultrasonograficznie okolicach — na szyi, w dołach pachowych i pachwinach. Samo powiększenie węzła nie jest jeszcze niepokojące, bo najczęściej wynika ze zwykłej infekcji. Istotny jest jego wygląd: węzeł odczynowy zachowuje owalny kształt i widoczną wnękę tłuszczową z centralnym unaczynieniem, natomiast węzeł podejrzany staje się kulisty, traci wnękę i wykazuje nieregularne unaczynienie obwodowe. USG z Dopplerem pozwala ocenić wszystkie te cechy.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pozycja zależy od badanej okolicy — przy węzłach szyjnych pacjent leży z odchyloną głową, przy pachowych z ręką uniesioną za głowę. Lekarz nakłada żel i systematycznie przeszukuje daną okolicę głowicą, mierząc znalezione węzły i oceniając ich kształt, granice oraz zachowanie wnęki. Następnie włącza Doppler i ocenia typ unaczynienia. Badanie jest bezbolesne i zwykle obejmuje kilka okolic naraz, gdy trzeba określić zasięg powiększenia.",
    },
    prep: [
      "Badanie nie wymaga żadnego przygotowania",
      "Odzież umożliwiająca odsłonięcie badanej okolicy",
      "Informacja o przebytych ostatnio infekcjach",
      "Wyniki wcześniejszych badań obrazowych, jeśli były wykonywane",
    ],
    indications: [
      "Wyczuwalne powiększenie węzłów chłonnych",
      "Utrzymująca się limfadenopatia po infekcji",
      "Diagnostyka onkologiczna — ocena zasięgu",
      "Monitorowanie znanych zmian węzłowych",
      "Gorączka o nieustalonej przyczynie",
    ],
  },
  {
    slug: "usg-oplucnej",
    title: "USG opłucnej",
    cat: "USG / Doppler",
    metaTitle: "USG opłucnej Lublin — Elkardia",
    metaDescription: "USG jam opłucnowych — wykrywanie i ocena płynu w opłucnej, istotna w niewydolności serca. Elkardia, Lublin.",
    heroBody: "Ocena jam opłucnowych — wykrywa nawet niewielkie ilości płynu, znacznie czulej niż zdjęcie RTG klatki piersiowej.",
    duration: "ok. 15 minut",
    what: {
      heading: "Czym jest USG opłucnej?",
      body: "Badanie ocenia jamy opłucnowe pod kątem obecności płynu i zmian w obrębie samej opłucnej. W wykrywaniu płynu ultrasonografia jest wyraźnie czulsza od klasycznego zdjęcia RTG — uwidacznia już kilkadziesiąt mililitrów, podczas gdy na zdjęciu płyn staje się widoczny dopiero przy znacznie większej objętości. Dla kardiologa to badanie szczególnie istotne, bo płyn w opłucnej jest częstym objawem zaostrzenia niewydolności serca, a jego ilość dobrze obrazuje skuteczność leczenia odwadniającego.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent siada, najlepiej tyłem do lekarza, z rękami skrzyżowanymi z przodu — taka pozycja rozsuwa łopatki i otwiera przestrzenie międzyżebrowe. Lekarz nakłada żel i przykłada głowicę w kolejnych przestrzeniach międzyżebrowych, oceniając obie strony porównawczo. Płyn jest w obrazie USG dobrze widoczny, a jego objętość szacujemy pomiarem. W trakcie badania prosimy o spokojny, głęboki oddech. U pacjentów, którzy nie mogą siedzieć, badanie wykonujemy w pozycji półleżącej.",
    },
    prep: [
      "Badanie nie wymaga żadnego przygotowania",
      "Ubranie łatwe do zdjęcia — konieczne odsłonięcie pleców",
      "Aktualna masa ciała — istotna przy ocenie leczenia odwadniającego",
      "Wyniki wcześniejszego RTG klatki piersiowej, jeśli było wykonane",
    ],
    indications: [
      "Duszność i podejrzenie płynu w opłucnej",
      "Zaostrzenie niewydolności serca",
      "Monitorowanie skuteczności leczenia odwadniającego",
      "Kontrola po przebytym zapaleniu płuc",
      "Kwalifikacja i nawigacja przed punkcją opłucnej",
    ],
  },
  {
    slug: "usg-doppler-tetnic-szyjnych",
    title: "USG Doppler tętnic szyjnych",
    cat: "USG / Doppler",
    metaTitle: "USG Doppler tętnic szyjnych Lublin — Elkardia",
    metaDescription: "USG Doppler tętnic szyjnych i kręgowych — ocena blaszek miażdżycowych, zwężeń i ryzyka udaru. Elkardia, Lublin.",
    heroBody: "Ocena tętnic szyjnych i kręgowych — wykrywa blaszki miażdżycowe i zwężenia zwiększające ryzyko udaru mózgu.",
    duration: "ok. 30 minut",
    what: {
      heading: "Czym jest Doppler tętnic szyjnych?",
      body: "Badanie ocenia tętnice szyjne i kręgowe — naczynia doprowadzające krew do mózgu. Obrazuje ich ścianę, mierzy grubość kompleksu intima-media, wykrywa blaszki miażdżycowe i za pomocą pomiaru prędkości przepływu określa stopień ewentualnego zwężenia. To jedno z najważniejszych badań w ocenie ryzyka udaru niedokrwiennego. Ma też wymiar szerszy: tętnice szyjne są dostępnym oknem na cały układ naczyniowy, a stwierdzona w nich miażdżyca wskazuje na podwyższone ryzyko sercowo-naczyniowe w całym organizmie.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent kładzie się na plecach z głową lekko odchyloną i obróconą w bok. Lekarz nakłada żel i bada kolejno obie strony szyi, obrazując tętnicę szyjną wspólną, jej podział oraz tętnice szyjną wewnętrzną i zewnętrzną, a na koniec tętnice kręgowe. Ocenia ścianę naczynia i obecność blaszek, następnie włącza Doppler i mierzy prędkości przepływu — to na ich podstawie wylicza stopień zwężenia. W trakcie badania słychać charakterystyczny szum przepływającej krwi.",
    },
    prep: [
      "Badanie nie wymaga żadnego przygotowania ani bycia na czczo",
      "Odzież z dekoltem, umożliwiająca odsłonięcie szyi",
      "Zdjęcie łańcuszków i naszyjników",
      "Aktualny lipidogram i wyniki poprzednich badań Doppler — do porównania",
    ],
    indications: [
      "Przebyty udar mózgu lub TIA",
      "Szmer nad tętnicą szyjną",
      "Ocena ryzyka sercowo-naczyniowego przy miażdżycy",
      "Kwalifikacja przed operacją kardiochirurgiczną",
      "Zawroty głowy i zaburzenia równowagi",
    ],
  },
  {
    slug: "usg-doppler-tetnic-mozgowych",
    title: "USG Doppler tętnic mózgowych",
    cat: "USG / Doppler",
    metaTitle: "USG Doppler tętnic mózgowych (przezczaszkowy) Lublin — Elkardia",
    metaDescription: "Przezczaszkowy Doppler tętnic mózgowych — ocena przepływu w naczyniach wewnątrzczaszkowych i krążenia obocznego. Elkardia, Lublin.",
    heroBody: "Przezczaszkowa ocena przepływu w naczyniach wewnątrz czaszki — uzupełnia badanie tętnic szyjnych o obraz krążenia mózgowego.",
    duration: "ok. 30–40 minut",
    what: {
      heading: "Czym jest Doppler przezczaszkowy?",
      body: "Doppler przezczaszkowy ocenia przepływ w naczyniach leżących wewnątrz czaszki — tętnicach mózgu przednich, środkowych i tylnych oraz w układzie kręgowo-podstawnym. Kość czaszki jest dla ultradźwięków barierą, dlatego badanie wykonujemy przez naturalne okna akustyczne: cienką łuskę kości skroniowej, oczodół i otwór potyliczny. Badanie pokazuje, jak zwężenia stwierdzone w tętnicach szyjnych przekładają się na rzeczywisty przepływ mózgowy, i pozwala ocenić wydolność krążenia obocznego.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent kładzie się na plecach. Lekarz nakłada żel i przykłada głowicę o niskiej częstotliwości kolejno w okolicy skroni, nad oczodołem i pod potylicą, poszukując okien akustycznych i identyfikując poszczególne naczynia po kierunku oraz charakterze przepływu. Mierzy prędkości i wskaźniki oporu. Badanie jest bezbolesne, ale wymaga cierpliwości i spokojnego leżenia — u części osób, zwłaszcza starszych, okno skroniowe bywa słabo przepuszczalne, co utrudnia badanie.",
    },
    prep: [
      "Badanie nie wymaga żadnego przygotowania",
      "Bez kawy i papierosów na 2 godziny przed badaniem — wpływają na przepływ mózgowy",
      "Rozpuszczone włosy, bez upięć w okolicy skroni",
      "Wynik Dopplera tętnic szyjnych, jeśli był wykonany",
    ],
    indications: [
      "Przebyty udar mózgu lub TIA",
      "Istotne zwężenie tętnicy szyjnej — ocena następstw",
      "Ocena krążenia obocznego",
      "Zawroty głowy i zaburzenia neurologiczne",
      "Poszukiwanie przecieku prawo-lewego",
    ],
  },
  {
    slug: "usg-doppler-tetnic-konczyn",
    title: "USG Doppler tętnic kończyn",
    cat: "USG / Doppler",
    metaTitle: "USG Doppler tętnic kończyn Lublin — Elkardia",
    metaDescription: "USG Doppler tętnic kończyn dolnych i górnych — diagnostyka miażdżycy, zwężeń i niedokrwienia kończyn. Elkardia, Lublin.",
    heroBody: "Ocena tętnic kończyn dolnych i górnych — diagnostyka miażdżycy zarostowej, zwężeń i chromania przestankowego.",
    duration: "ok. 30–45 minut",
    what: {
      heading: "Czym jest Doppler tętnic kończyn?",
      body: "Badanie ocenia tętnice kończyn na całym przebiegu — od tętnic biodrowych, przez udowe i podkolanowe, aż po tętnice goleni. Wykrywa blaszki miażdżycowe, mierzy stopień zwężeń i ocenia charakter przepływu poniżej przeszkody. Najczęstszym powodem wykonania jest chromanie przestankowe, czyli ból łydek zmuszający do zatrzymania się po przejściu określonego dystansu. Badanie pozwala też ocenić drożność pomostów i stentów naczyniowych oraz zaplanować ewentualne leczenie zabiegowe.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent kładzie się na plecach z odsłoniętymi kończynami. Lekarz nakłada żel i prowadzi głowicę wzdłuż przebiegu tętnic, oceniając kolejne odcinki obustronnie i porównawczo. W każdym segmencie ocenia ścianę naczynia, obecność blaszek, a następnie za pomocą Dopplera mierzy prędkość i analizuje kształt fali przepływu — jej spłaszczenie poniżej zwężenia jest istotną wskazówką. Badanie jest bezbolesne, ale ze względu na długi przebieg naczyń trwa dłużej niż typowe USG.",
    },
    prep: [
      "Badanie nie wymaga bycia na czczo",
      "Odzież umożliwiająca odsłonięcie całych kończyn — najlepiej krótkie spodenki",
      "Bez balsamów i kremów na skórze nóg",
      "Informacja o dystansie chromania i przebytych zabiegach naczyniowych",
    ],
    indications: [
      "Chromanie przestankowe — ból łydek przy chodzeniu",
      "Ból spoczynkowy kończyn",
      "Owrzodzenia i trudno gojące się rany",
      "Brak lub osłabienie tętna na kończynie",
      "Kontrola drożności pomostów i stentów",
    ],
  },
  {
    slug: "usg-doppler-zyl-konczyn",
    title: "USG Doppler żył kończyn",
    cat: "USG / Doppler",
    metaTitle: "USG Doppler żył kończyn Lublin — Elkardia",
    metaDescription: "USG Doppler żył kończyn dolnych — diagnostyka zakrzepicy żył głębokich i niewydolności żylnej. Elkardia, Lublin.",
    heroBody: "Ocena żył kończyn dolnych — podstawowe badanie w diagnostyce zakrzepicy żył głębokich i przewlekłej niewydolności żylnej.",
    duration: "ok. 30–45 minut",
    what: {
      heading: "Czym jest Doppler żył kończyn?",
      body: "Badanie ocenia układ żył głębokich i powierzchownych kończyn dolnych. Ma dwa główne zastosowania. Pierwsze to diagnostyka zakrzepicy żył głębokich — stanu wymagającego pilnego leczenia, ponieważ oderwany skrzep może wywołać zatorowość płucną. Drugie to ocena przewlekłej niewydolności żylnej i żylaków, gdzie badamy wydolność zastawek i kierunek przepływu. Kluczowym elementem jest próba uciskowa: żyła zdrowa zapada się pod uciskiem głowicy, żyła wypełniona skrzepliną pozostaje nieodkształcalna.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Diagnostykę zakrzepicy wykonujemy zwykle na leżąco, natomiast ocenę żylaków i wydolności zastawek najlepiej przeprowadzić w pozycji stojącej, gdy żyły są maksymalnie wypełnione. Lekarz nakłada żel i prowadzi głowicę wzdłuż przebiegu żył, systematycznie uciskając naczynie co kilka centymetrów. Następnie ocenia przepływ w Dopplerze i prosi o wykonanie próby Valsalvy oraz o ucisk łydki, co pozwala ocenić kierunek przepływu i wykryć refluks przez niewydolne zastawki.",
    },
    prep: [
      "Badanie nie wymaga bycia na czczo",
      "Odzież umożliwiająca odsłonięcie całych nóg",
      "Bez balsamów i kremów na skórze nóg",
      "Przy podejrzeniu zakrzepicy badanie wykonujemy pilnie, bez odkładania",
      "Wynik D-dimerów, jeśli był oznaczany",
    ],
    indications: [
      "Podejrzenie zakrzepicy żył głębokich — obrzęk i ból łydki",
      "Żylaki kończyn dolnych",
      "Przewlekła niewydolność żylna, obrzęki, zmiany skórne",
      "Owrzodzenia żylne podudzi",
      "Kwalifikacja do leczenia zabiegowego żylaków",
    ],
  },

  // ── Sen i oddech ──
  {
    slug: "holter-rr-bezdech-senny",
    title: "Holter RR bezdech senny",
    cat: "Sen i oddech",
    metaTitle: "Holter ciśnieniowy w diagnostyce bezdechu sennego Lublin — Elkardia",
    metaDescription: "Holter ciśnieniowy w kierunku bezdechu sennego — analiza nocnego profilu ciśnienia wskazująca na zaburzenia oddychania. Elkardia, Lublin.",
    heroBody: "Holter ciśnieniowy z analizą nocnego profilu — brak nocnego spadku ciśnienia jest jednym z pierwszych sygnałów bezdechu sennego.",
    duration: "24 godziny rejestracji",
    what: {
      heading: "Co ciśnienie mówi o bezdechu?",
      body: "U zdrowej osoby ciśnienie w nocy spada o co najmniej 10 procent względem wartości dziennych. W bezdechu sennym każdy epizod zatrzymania oddechu wywołuje mikroprzebudzenie i gwałtowny wyrzut adrenaliny, przez co nocny spadek zanika — a u części pacjentów ciśnienie w nocy jest nawet wyższe niż w dzień. Taki profil, opisywany jako non-dipping lub reverse dipping, jest silnym sygnałem ostrzegawczym. Holter ciśnieniowy nie zastępuje badania snu, ale często jako pierwszy naprowadza na właściwy trop.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Na ramię zakładamy mankiet połączony z niewielkim aparatem noszonym na pasku. Urządzenie mierzy ciśnienie automatycznie co 15–30 minut w dzień i co 30–60 minut w nocy. Kluczowa jest noc spędzona we własnym łóżku i w zwykłym rytmie — dlatego prosimy, by nie zmieniać pory zasypiania. Rodzina może pomóc, notując zaobserwowane chrapanie i bezdechy. Po dobie generujemy raport z profilem dobowym, a lekarz ocenia zachowanie ciśnienia w nocy i decyduje o dalszej diagnostyce.",
    },
    prep: [
      "Luźna koszula z rękawem",
      "Zachowanie zwykłej pory snu",
      "Notowanie chrapania i zaobserwowanych bezdechów",
      "Bez alkoholu w dniu badania — nasila bezdechy i zaburza wynik",
    ],
    indications: [
      "Chrapanie i zaobserwowane bezdechy",
      "Nadciśnienie oporne na leczenie",
      "Senność dzienna i poranne bóle głowy",
      "Podejrzenie braku nocnego spadku ciśnienia",
      "Migotanie przedsionków o niejasnej przyczynie",
    ],
  },
  {
    slug: "badanie-snu-w-domu",
    title: "Pełne badanie snu w sypialni pacjenta",
    cat: "Sen i oddech",
    metaTitle: "Badanie snu w domu pacjenta Lublin — Elkardia",
    metaDescription: "Pełna poligrafia snu wykonywana w domu pacjenta — diagnostyka bezdechu sennego we własnym łóżku. Elkardia, Lublin.",
    heroBody: "Pełne badanie snu przeprowadzane we własnej sypialni pacjenta — bez pracowni, bez obcego łóżka, w naturalnych warunkach.",
    duration: "jedna noc",
    what: {
      heading: "Na czym polega badanie snu w domu?",
      body: "To pełna diagnostyka zaburzeń oddychania podczas snu, przeprowadzana w domu pacjenta zamiast w pracowni. Rejestrujemy przepływ powietrza przez nos i usta, ruchy oddechowe klatki piersiowej i brzucha, saturację, tętno, chrapanie i pozycję ciała. Na tej podstawie wyliczamy wskaźnik AHI, czyli liczbę bezdechów i spłyceń oddechu na godzinę snu — parametr rozstrzygający o rozpoznaniu i jego stopniu. Badanie we własnym łóżku daje obraz bliższy rzeczywistości niż noc spędzona w obcym miejscu.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Urządzenie odbieracie w pracowni wraz z instruktażem albo dostarczamy je do domu. Wieczorem, przed snem, pacjent samodzielnie zakłada czujniki: kaniulę pod nosem, pasy na klatce piersiowej i brzuchu oraz pulsoksymetr na palcu. Zakładanie zajmuje kilka minut i jest proste. Następnie kładzie się spać jak zwykle — bez zmiany pory ani nawyków. Rano zdejmuje czujniki i zwraca urządzenie, a lekarz analizuje zapis i wylicza AHI, omawiając wynik i dalsze postępowanie na wizycie.",
    },
    prep: [
      "Bez alkoholu i leków nasennych w dniu badania — zafałszowują wynik",
      "Bez drzemki po południu",
      "Zachowanie zwykłej pory zasypiania",
      "Kąpiel przed założeniem czujników, bez balsamów i kremów",
      "Bez lakieru na paznokciach — zaburza odczyt pulsoksymetru",
    ],
    indications: [
      "Głośne chrapanie i zaobserwowane bezdechy",
      "Nadmierna senność dzienna",
      "Poranne bóle głowy i uczucie niewyspania",
      "Nadciśnienie oporne na leczenie",
      "Migotanie przedsionków i nocne zaburzenia rytmu",
      "Otyłość z objawami nocnymi",
    ],
  },
  {
    slug: "spirometria",
    title: "Spirometria",
    cat: "Sen i oddech",
    metaTitle: "Spirometria Lublin — Elkardia",
    metaDescription: "Spirometria — ocena wydolności płuc, diagnostyka astmy i POChP oraz różnicowanie duszności. Elkardia, Lublin.",
    heroBody: "Podstawowe badanie czynnościowe płuc — mierzy objętości i przepływy oddechowe, różnicując duszność sercową od płucnej.",
    duration: "ok. 20–30 minut",
    what: {
      heading: "Czym jest spirometria?",
      body: "Spirometria mierzy objętość powietrza, którą pacjent jest w stanie wydmuchać, oraz szybkość tego wydechu. Na tej podstawie ocenia drożność dróg oddechowych i pozwala rozpoznać obturację charakterystyczną dla astmy i POChP. W kardiologii ma szczególne znaczenie przy różnicowaniu duszności — objaw ten jest tak samo typowy dla niewydolności serca, jak dla chorób płuc, a spirometria pomaga ustalić, który mechanizm dominuje. Wiarygodność badania w dużym stopniu zależy od współpracy pacjenta.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent siada prosto, zakłada klips na nos i szczelnie obejmuje ustnik wargami. Na polecenie technika wykonuje maksymalnie głęboki wdech, a następnie najsilniejszy i najdłuższy możliwy wydech — to najważniejszy moment całego badania. Manewr powtarzamy co najmniej trzykrotnie, aby uzyskać powtarzalny wynik, z przerwami na odpoczynek. Czasem badanie rozszerzamy o próbę rozkurczową: po podaniu leku wziewnego powtarzamy pomiar, sprawdzając, czy obturacja jest odwracalna.",
    },
    prep: [
      "Bez palenia papierosów na 24 godziny przed badaniem",
      "Bez dużego wysiłku fizycznego na 30 minut przed badaniem",
      "Lekki posiłek — nie badamy bezpośrednio po obfitym jedzeniu",
      "Ustalenie z lekarzem odstawienia leków wziewnych przed badaniem",
      "Luźne ubranie nieograniczające ruchów klatki piersiowej",
    ],
    indications: [
      "Duszność o niejasnej przyczynie — sercowa czy płucna",
      "Przewlekły kaszel",
      "Podejrzenie astmy lub POChP",
      "Palenie papierosów — badanie przesiewowe",
      "Kwalifikacja przed operacją",
      "Monitorowanie leczenia chorób płuc",
    ],
  },

  // ── Ocena ryzyka ──
  {
    slug: "wskaznik-abi",
    title: "Wskaźnik ABI (niedokrwienie kończyn)",
    cat: "Ocena ryzyka",
    metaTitle: "Wskaźnik kostka-ramię ABI Lublin — Elkardia",
    metaDescription: "Pomiar wskaźnika kostka-ramię (ABI) — szybka i nieinwazyjna ocena niedokrwienia kończyn dolnych. Elkardia, Lublin.",
    heroBody: "Prosty pomiar porównujący ciśnienie na kostce i ramieniu — wykrywa miażdżycę kończyn dolnych, często zanim pojawią się objawy.",
    duration: "ok. 20 minut",
    what: {
      heading: "Czym jest wskaźnik ABI?",
      body: "Wskaźnik kostka-ramię to iloraz ciśnienia skurczowego zmierzonego na kostce i na ramieniu. U osoby zdrowej wartości te są zbliżone, a wskaźnik wynosi około 1,0. Jeśli tętnice kończyny są zwężone przez miażdżycę, ciśnienie na kostce spada i wskaźnik maleje — wartość poniżej 0,9 potwierdza miażdżycę zarostową tętnic kończyn dolnych. Badanie jest tanie, szybkie i nieinwazyjne, a jego wynik ma znaczenie wykraczające poza same nogi: obniżony ABI jest niezależnym markerem ryzyka zawału i udaru.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent kładzie się na plecach i odpoczywa przez kilka minut, co jest warunkiem miarodajnego pomiaru. Następnie zakładamy mankiety na oba ramiona i obie kostki. Ciśnienie mierzymy z użyciem sondy dopplerowskiej przykładanej nad tętnicą — to dokładniejsze niż zwykły aparat, bo pozwala wychwycić moment pojawienia się przepływu nawet przy słabo wyczuwalnym tętnie. Z uzyskanych wartości wyliczamy wskaźnik osobno dla każdej kończyny. Badanie jest bezbolesne.",
    },
    prep: [
      "Kilka minut odpoczynku w pozycji leżącej przed pomiarem",
      "Odzież umożliwiająca odsłonięcie ramion i kostek",
      "Bez kawy i papierosów na godzinę przed badaniem",
      "Informacja o dystansie chromania, jeśli występuje",
    ],
    indications: [
      "Chromanie przestankowe",
      "Cukrzyca — badanie przesiewowe",
      "Palenie papierosów i miażdżyca w innych obszarach",
      "Ocena globalnego ryzyka sercowo-naczyniowego",
      "Trudno gojące się rany na stopach",
    ],
  },
  {
    slug: "analiza-skladu-ciala",
    title: "Analiza składu ciała (SECA-285)",
    cat: "Ocena ryzyka",
    metaTitle: "Analiza składu ciała SECA-285 Lublin — Elkardia",
    metaDescription: "Profesjonalna analiza składu ciała na urządzeniu SECA-285 — pomiar masy mięśniowej, tłuszczowej i nawodnienia. Elkardia, Lublin.",
    heroBody: "Profesjonalna analiza składu ciała na medycznym urządzeniu SECA-285 — rozdziela masę mięśniową, tłuszczową i wodę organizmu.",
    duration: "ok. 15 minut",
    what: {
      heading: "Czym jest analiza składu ciała?",
      body: "Sama masa ciała niewiele mówi — dwie osoby o identycznej wadze mogą mieć zupełnie inny skład organizmu. Analizator SECA-285 wykorzystuje bioimpedancję, przepuszczając przez ciało nieodczuwalny prąd o bardzo niskim natężeniu i mierząc opór poszczególnych tkanek. Na tej podstawie wylicza masę mięśniową, masę tłuszczową i jej rozkład, w tym kluczowy tłuszcz trzewny, oraz zawartość wody. To urządzenie klasy medycznej, znacznie dokładniejsze od domowych wag z funkcją pomiaru tkanki tłuszczowej.",
    },
    how: {
      heading: "Jak przebiega badanie?",
      body: "Pacjent staje boso na platformie analizatora i chwyta dłońmi uchwyty z elektrodami, pozostając nieruchomo przez kilkadziesiąt sekund. Pomiar jest całkowicie bezbolesny — przepływającego prądu w ogóle się nie czuje. Wynik pojawia się od razu w formie szczegółowego raportu z rozkładem tkanek i odniesieniem do norm dla wieku i płci. Raport omawiamy na miejscu, tłumacząc poszczególne parametry. Kolejne badania warto wykonywać o podobnej porze dnia, by wyniki były porównywalne.",
    },
    prep: [
      "Na czczo lub co najmniej 3 godziny po posiłku",
      "Bez wysiłku fizycznego i sauny w dniu badania",
      "Dobre nawodnienie, ale bez wypijania dużej ilości płynów tuż przed",
      "Bez alkoholu przez 24 godziny przed badaniem",
      "Pomiar kolejny warto wykonać o podobnej porze dnia",
    ],
    indications: [
      "Otyłość i nadwaga — ocena wyjściowa",
      "Monitorowanie postępów redukcji masy ciała",
      "Ocena ryzyka metabolicznego i tłuszczu trzewnego",
      "Współpraca z dietetykiem",
      "Ocena nawodnienia w niewydolności serca",
    ],
  },
  {
    slug: "pomiar-bmi",
    title: "Profesjonalny pomiar BMI",
    cat: "Ocena ryzyka",
    metaTitle: "Profesjonalny pomiar BMI Lublin — Elkardia",
    metaDescription: "Profesjonalny pomiar BMI wraz z obwodem talii i oceną ryzyka metabolicznego. Elkardia, Lublin.",
    heroBody: "Rzetelny pomiar wskaźnika masy ciała uzupełniony obwodem talii — z interpretacją, a nie samą liczbą.",
    duration: "ok. 10 minut",
    what: {
      heading: "Po co mierzyć BMI w gabinecie?",
      body: "Wskaźnik masy ciała można policzyć samodzielnie, ale jego wartość zależy od rzetelności pomiaru wzrostu i masy — a te wykonane w domu bywają nieprecyzyjne. W gabinecie mierzymy oba parametry na sprzęcie medycznym i uzupełniamy je o obwód talii, który jest lepszym wskaźnikiem ryzyka sercowo-naczyniowego niż samo BMI. Warto pamiętać o ograniczeniu wskaźnika: BMI nie odróżnia mięśni od tłuszczu, więc u osób umięśnionych bywa mylące. Dlatego zawsze interpretujemy go w kontekście, a nie jako samodzielną liczbę.",
    },
    how: {
      heading: "Jak przebiega pomiar?",
      body: "Mierzymy masę ciała na wadze medycznej oraz wzrost na wzrostomierzu — pacjent stoi boso, w lekkim ubraniu. Następnie mierzymy obwód talii w połowie odległości między dolnym żebrem a talerzem biodrowym, na wysokości pępka, przy spokojnym wydechu. Z uzyskanych wartości wyliczamy BMI i odnosimy je do norm, a obwód talii oceniamy oddzielnie względem progów ryzyka. Wynik omawiamy od razu, tłumacząc, co oznacza w kontekście indywidualnego ryzyka sercowo-naczyniowego.",
    },
    prep: [
      "Najlepiej rano, na czczo",
      "Lekkie ubranie, buty do zdjęcia",
      "Bez obfitego posiłku bezpośrednio przed pomiarem",
      "Kolejne pomiary warto wykonywać o podobnej porze dnia",
    ],
    indications: [
      "Ocena wyjściowa przy nadwadze i otyłości",
      "Monitorowanie redukcji masy ciała",
      "Ocena ryzyka sercowo-naczyniowego i metabolicznego",
      "Kwalifikacja do współpracy z dietetykiem",
      "Badanie okresowe i profilaktyczne",
    ],
  },
  {
    slug: "ocena-ryzyka-udaru",
    title: "Ocena ryzyka udaru mózgowego",
    cat: "Ocena ryzyka",
    metaTitle: "Ocena ryzyka udaru mózgu (CHA2DS2-VASc) Lublin — Elkardia",
    metaDescription: "Ocena ryzyka udaru mózgu w skali CHA2DS2-VASc — kwalifikacja do leczenia przeciwkrzepliwego przy migotaniu przedsionków. Elkardia, Lublin.",
    heroBody: "Ustrukturyzowana ocena ryzyka udaru w skali CHA2DS2-VASc — podstawa decyzji o leczeniu przeciwkrzepliwym w migotaniu przedsionków.",
    duration: "ok. 30 minut (konsultacja)",
    what: {
      heading: "Na czym polega ocena ryzyka udaru?",
      body: "U pacjentów z migotaniem przedsionków krew zalega w przedsionku i może tworzyć skrzepliny, które przemieszczają się do mózgu, wywołując udar. Ryzyko to szacujemy w skali CHA2DS2-VASc, przyznając punkty za wiek, płeć, nadciśnienie, cukrzycę, niewydolność serca, chorobę naczyń oraz przebyty udar. Suma punktów przekłada się bezpośrednio na decyzję terapeutyczną: od jakiego progu włączyć leczenie przeciwkrzepliwe. To jedna z najważniejszych decyzji w kardiologii, bo skutecznie zapobiega udarom.",
    },
    how: {
      heading: "Jak przebiega ocena?",
      body: "Ocena odbywa się w ramach konsultacji kardiologicznej. Lekarz zbiera dokładny wywiad, przegląda dokumentację i wyniki badań, a następnie wylicza punktację w skali CHA2DS2-VASc. Równolegle ocenia ryzyko krwawienia, ponieważ decyzja o leczeniu przeciwkrzepliwym zawsze jest zestawieniem obu tych ryzyk. Na tej podstawie proponuje konkretne postępowanie i omawia je z pacjentem — wraz z korzyściami, ograniczeniami i alternatywami. Wynik oceny wraz z zaleceniami trafia do dokumentacji.",
    },
    prep: [
      "Pełna dokumentacja medyczna, w tym karty wypisowe",
      "Aktualna lista wszystkich przyjmowanych leków",
      "Wyniki badań krwi, zwłaszcza kreatyniny i morfologii",
      "Zapisy EKG i Holtera dokumentujące migotanie przedsionków",
    ],
    indications: [
      "Rozpoznane migotanie lub trzepotanie przedsionków",
      "Kwalifikacja do leczenia przeciwkrzepliwego",
      "Weryfikacja dotychczasowego leczenia",
      "Przebyty udar lub TIA",
      "Okresowa reocena ryzyka",
    ],
  },
  {
    slug: "ocena-ryzyka-krwawienia",
    title: "Ocena ryzyka krwawienia",
    cat: "Ocena ryzyka",
    metaTitle: "Ocena ryzyka krwawienia (HAS-BLED) Lublin — Elkardia",
    metaDescription: "Ocena ryzyka krwawienia w skali HAS-BLED — bezpieczne prowadzenie leczenia przeciwkrzepliwego. Elkardia, Lublin.",
    heroBody: "Ocena ryzyka krwawienia w skali HAS-BLED — identyfikuje czynniki, które można modyfikować, by bezpiecznie prowadzić leczenie przeciwkrzepliwe.",
    duration: "ok. 30 minut (konsultacja)",
    what: {
      heading: "Po co oceniać ryzyko krwawienia?",
      body: "Leczenie przeciwkrzepliwe chroni przed udarem, ale zwiększa ryzyko krwawień — i te dwa ryzyka trzeba zestawić. Do oceny służy skala HAS-BLED, uwzględniająca nadciśnienie, funkcję nerek i wątroby, przebyte udary i krwawienia, chwiejne INR, wiek oraz leki i alkohol. Kluczowe jest właściwe rozumienie wyniku: wysoka punktacja prawie nigdy nie oznacza rezygnacji z leczenia. Wskazuje natomiast czynniki możliwe do modyfikacji — jak niekontrolowane ciśnienie czy alkohol — i pacjentów wymagających częstszych kontroli.",
    },
    how: {
      heading: "Jak przebiega ocena?",
      body: "Ocena odbywa się podczas konsultacji kardiologicznej, zwykle łącznie z oceną ryzyka udaru. Lekarz zbiera wywiad dotyczący przebytych krwawień, chorób wątroby i nerek, spożycia alkoholu oraz wszystkich przyjmowanych leków — także tych dostępnych bez recepty, bo popularne leki przeciwbólowe istotnie zwiększają ryzyko. Następnie wylicza punktację HAS-BLED i zestawia ją z ryzykiem udaru. Na tej podstawie proponuje postępowanie i wskazuje czynniki do modyfikacji.",
    },
    prep: [
      "Pełna lista leków, w tym preparatów bez recepty i suplementów",
      "Wyniki morfologii, kreatyniny i prób wątrobowych",
      "Informacja o przebytych krwawieniach i ich okolicznościach",
      "Dokumentacja dotychczasowych wartości INR, jeśli dotyczy",
    ],
    indications: [
      "Kwalifikacja do leczenia przeciwkrzepliwego",
      "Prowadzone leczenie przeciwkrzepliwe — reocena",
      "Przebyte krwawienie w trakcie leczenia",
      "Chwiejne wartości INR",
      "Wielolekowość i podeszły wiek",
    ],
  },
  {
    slug: "euroscore",
    title: "Ocena EuroSCORE (operacja serca)",
    cat: "Ocena ryzyka",
    metaTitle: "Ocena EuroSCORE II przed operacją serca Lublin — Elkardia",
    metaDescription: "Ocena ryzyka operacji kardiochirurgicznej w skali EuroSCORE II — obiektywne oszacowanie ryzyka zabiegu. Elkardia, Lublin.",
    heroBody: "Ocena ryzyka operacji kardiochirurgicznej w skali EuroSCORE II — obiektywna liczba wspierająca decyzję o wyborze metody leczenia.",
    duration: "ok. 30–45 minut (konsultacja)",
    what: {
      heading: "Czym jest EuroSCORE II?",
      body: "EuroSCORE II to walidowana skala szacująca ryzyko zgonu okołooperacyjnego przy zabiegach kardiochirurgicznych. Uwzględnia wiek, płeć, funkcję nerek, frakcję wyrzutową lewej komory, pilność zabiegu, choroby współistniejące i rodzaj planowanej operacji. Wynik podawany jest jako procentowe ryzyko. Ma to praktyczne znaczenie przy wyborze metody leczenia — na przykład przy zwężeniu zastawki aortalnej pomaga zdecydować między klasyczną operacją a przezcewnikowym wszczepieniem zastawki TAVI u pacjentów wysokiego ryzyka.",
    },
    how: {
      heading: "Jak przebiega ocena?",
      body: "Ocena odbywa się w ramach konsultacji kardiologicznej. Lekarz zbiera szczegółowy wywiad i przegląda całą dokumentację — kluczowe są aktualne echo serca z frakcją wyrzutową, wyniki koronarografii oraz badania krwi z kreatyniną. Na tej podstawie wprowadza dane do kalkulatora i uzyskuje procentowe ryzyko. Wynik omawia z pacjentem, tłumacząc, co konkretnie oznacza dana wartość i jak przekłada się na wybór metody leczenia. Ocena stanowi element dokumentacji przekazywanej do ośrodka kardiochirurgicznego.",
    },
    prep: [
      "Pełna dokumentacja medyczna i karty wypisowe",
      "Aktualne echo serca z oceną frakcji wyrzutowej",
      "Wynik koronarografii, jeśli była wykonana",
      "Aktualne badania krwi, zwłaszcza kreatynina",
      "Lista wszystkich przyjmowanych leków",
    ],
    indications: [
      "Kwalifikacja do operacji kardiochirurgicznej",
      "Wybór między operacją klasyczną a TAVI",
      "Ciężka wada zastawkowa",
      "Choroba wielonaczyniowa rozważana do pomostowania",
      "Konsultacja przed decyzją Heart Teamu",
    ],
  },
  {
    slug: "ocena-ryzyka-zabiegowego",
    title: "Ocena ryzyka zabiegowego",
    cat: "Ocena ryzyka",
    metaTitle: "Kardiologiczna ocena ryzyka przed operacją Lublin — Elkardia",
    metaDescription: "Konsultacja kardiologiczna przed operacją niekardiochirurgiczną — ocena ryzyka sercowo-naczyniowego i kwalifikacja do zabiegu. Elkardia, Lublin.",
    heroBody: "Kardiologiczna kwalifikacja przed operacją niekardiochirurgiczną — ocena ryzyka powikłań i przygotowanie pacjenta do zabiegu.",
    duration: "ok. 30–45 minut (konsultacja)",
    what: {
      heading: "Czym jest kardiologiczna ocena przedoperacyjna?",
      body: "Przed planowaną operacją — ortopedyczną, chirurgiczną czy onkologiczną — pacjenci z chorobami serca wymagają oceny kardiologicznej. Ryzyko zależy od dwóch rzeczy: stanu układu sercowo-naczyniowego oraz rodzaju samego zabiegu, bo operacje różnią się obciążeniem. Ocena obejmuje wydolność pacjenta, choroby współistniejące i wyniki badań, a często istotniejsze od samej kwalifikacji jest to, co po niej następuje: optymalizacja leczenia i decyzje o lekach przeciwkrzepliwych w okresie okołozabiegowym.",
    },
    how: {
      heading: "Jak przebiega ocena?",
      body: "Konsultacja zaczyna się od wywiadu i badania przedmiotowego, ze szczególnym uwzględnieniem tolerancji wysiłku — to jeden z najlepszych predyktorów powikłań. Lekarz przegląda dokumentację i wyniki, a w razie potrzeby zleca uzupełniające badania, najczęściej EKG i echo serca. Następnie ocenia ryzyko, wydaje opinię o kwalifikacji i ustala postępowanie z lekami: co odstawić, kiedy i czym ewentualnie zastąpić. Opinia w formie pisemnej trafia do zespołu operującego i anestezjologa.",
    },
    prep: [
      "Informacja o planowanym rodzaju i terminie operacji",
      "Pełna dokumentacja kardiologiczna",
      "Aktualna lista leków, zwłaszcza przeciwkrzepliwych i przeciwpłytkowych",
      "Aktualne badania krwi",
      "Wyniki wcześniejszego EKG i echa serca, jeśli były wykonywane",
    ],
    indications: [
      "Planowana operacja u pacjenta z chorobą serca",
      "Kwalifikacja anestezjologiczna wymagająca opinii kardiologa",
      "Decyzja o lekach przeciwkrzepliwych okołozabiegowo",
      "Przebyty zawał, stenty, wszczepiona zastawka",
      "Migotanie przedsionków przed operacją",
    ],
  },
  {
    slug: "ocena-ryzyka-ciazy",
    title: "Ocena ryzyka ciąży",
    cat: "Ocena ryzyka",
    metaTitle: "Kardiologiczna ocena ryzyka ciąży (mWHO) Lublin — Elkardia",
    metaDescription: "Kardiologiczna ocena ryzyka ciąży w skali mWHO — konsultacja dla kobiet z chorobą serca planujących ciążę. Elkardia, Lublin.",
    heroBody: "Kardiologiczna ocena ryzyka ciąży w klasyfikacji mWHO — dla kobiet z chorobą serca planujących ciążę lub już będących w ciąży.",
    duration: "ok. 45 minut (konsultacja)",
    what: {
      heading: "Na czym polega ocena ryzyka ciąży?",
      body: "Ciąża znacząco obciąża układ krążenia — objętość krwi rośnie o około połowę, a serce pracuje ciężej przez wiele miesięcy. U kobiet z chorobą serca wymaga to wcześniejszej oceny, najlepiej jeszcze przed zajściem w ciążę. Ryzyko klasyfikujemy w skali mWHO, od klasy I, gdzie jest ono porównywalne z populacją ogólną, po klasę IV, w której ciąża jest przeciwwskazana. Ocena obejmuje rodzaj wady, wydolność serca, ciśnienie płucne oraz — co bardzo istotne — bezpieczeństwo przyjmowanych leków.",
    },
    how: {
      heading: "Jak przebiega ocena?",
      body: "Konsultacja obejmuje szczegółowy wywiad, badanie oraz przegląd dokumentacji. Podstawą jest aktualne echo serca, dlatego zwykle wykonujemy je w trakcie wizyty lub bezpośrednio przed nią. Lekarz określa klasę mWHO i omawia ją z pacjentką — konkretnie, bez ogólników. Osobnym, kluczowym elementem jest weryfikacja leków: część preparatów kardiologicznych jest w ciąży przeciwwskazana i wymaga zamiany jeszcze przed poczęciem. Ustalamy też plan opieki i częstość kontroli w trakcie ciąży.",
    },
    prep: [
      "Najlepiej zgłosić się przed planowaną ciążą, a nie po jej stwierdzeniu",
      "Pełna dokumentacja kardiologiczna, w tym karty wypisowe z dzieciństwa",
      "Aktualne echo serca, jeśli było wykonane",
      "Lista wszystkich przyjmowanych leków",
      "Dokumentacja poprzednich ciąż, jeśli były",
    ],
    indications: [
      "Wrodzona lub nabyta wada serca u kobiety planującej ciążę",
      "Kardiomiopatia",
      "Przebyta operacja kardiochirurgiczna",
      "Arytmie wymagające leczenia",
      "Nadciśnienie płucne",
      "Weryfikacja bezpieczeństwa leków przed ciążą",
    ],
  },
]

export function getBadanieSubpage(slug: string): BadanieSubpageData | null {
  return badaniaSubpages.find(p => p.slug === slug) ?? null
}
